config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:'homes#top'
  get '/about' => 'homes#about'

  resources :categories,only: [:index]
  resources :users, only: [:show ,:edit, :update]
  resources :posts do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    get :search, on: :collection
  end

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/done', to: 'contacts#done', as: 'done'
  get 'contacts/confirm', to: redirect('/contacts/new')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
  
end

app/models/category.rb
class Category < ApplicationRecord

  belongs_to :post, optional: true

end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :name, presence: true
  validates :message, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  accepts_attachments_for :post_images, attachment: :image

  validates :title, presence: true
  validates :body, presence: true

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

end

app/models/post_image.rb
class PostImage < ApplicationRecord
  
  belongs_to :post
  attachment :image
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :posts , dependent: :destroy
         has_many :post_comments,dependent: :destroy
         has_many :favorites,dependent: :destroy
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top,:about,:index]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  

  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render:new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render:new
  end
  # 入力内容に誤りがあった場合、入力内容を保持したまま前のページに戻ってくれる:back

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render:new
    end
  end

  def done
  end
  # 送信完了画面のための記述

  private

  def contact_params
    params.require(:contact)
          .permit(:email, :name, :message)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @posts = Post.all
    @categories = Category.all
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!
before_action :correct_post,only: [:edit,:update]

  def new
    @post = Post.new
    @category = Category.all.map{ |category| [category.name, category.id,] }
  end

  def create
    @post = Post.new(post_params)
    @post.score = Language.get_data(post_params[:body])
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post.id)
    else
      @category = Category.all.map{ |category| [category.name, category.id,] }
      render :new
    end
  end

  def index
    if params[:category_id].present?
     @category = Category.find(params[:category_id])
     @posts = Post.where(category_id: params[:category_id]).page(params[:page]).reverse_order
     pp @posts
    else
     @posts = Post.page(params[:page]).reverse_order
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    if @post.category_id.present?
     @category = Category.find(@post.category_id)
    end
  end

  def edit
    @post = Post.find(params[:id])
    @category = Category.all.map{ |category| [category.name, category.id,] }
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post)
  end

  def correct_post
    @post = Post.find(params[:id])
   unless @post.user.id == current_user.id
    redirect_to posts_path
   end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def search
    @posts = Post.where('body LIKE ?', "%#{params[:name]}%").or(Post.where('title LIKE ?', "%#{params[:name]}%"))
    @is_search = true
    render :index
  end

  private

  def post_params
    params.require(:post).permit(:title,:body,:category_id, post_images_images: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!
before_action :correct_user, only: [:update,:edit]

def show
  @user = User.find(params[:id])
  @posts = @user.posts
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  @user.update(user_params)
  redirect_to user_path(@user.id)
end

def correct_user
  @user = User.find(params[:id])
 unless @user.id == current_user.id
  redirect_to root_path
 end
end

  private

def user_params
  params.require(:user).permit(:name, :email)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/confirm.html.erb
<div class="container">

  <div class="row border-bottom mt-5">
    <p><i class="bi bi-person-fill ml-4 pr-2"></i>入力内容の確認</p>
  </div>
  <div class='row mt-3'>
    <p class='col-md-2'>名前：</p>
    <p class='col-md-2'><%= @contact.name %></p>
  </div>

  <div class='row mt-3'>
    <p class='col-md-2'>メールアドレス：</p>
    <p class='col-md-2'><%= @contact.email %></p>
  </div>

  <div class='row'>
    <p class='col-md-2'>お問合せ内容：</p>
    <p class='col-md-2'><%= @contact.message %></p>
  </div>
  <div class="row">
    <%= form_for(@contact) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :message %>
      <div class="col-md-5 mt-3"><%= f.submit '送信', class: 'btn btn-outline-dark mr-3' %></div>
    <% end %>
    <%= form_for @contact, url: back_path do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :message %>
      <div class="col-md-2 mt-3"><%= f.submit '入力画面に戻る', class:'btn btn-outline-secondary' %></div>
    <% end %>

app/views/contacts/done.html.erb
<div class="container">
  <div class="row border-bottom mt-5">
   <strong class="mb-3"><i class="bi bi-stars mr-2"></i>送信完了</strong>
  </div>
  <div class="row pt-4">
   <p>お問い合わせを受け付けました。</p>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">

  <div class="error-text pt-4">
   <% if @contact.errors.any? %>
    <i class="bi bi-exclamation-diamond"></i> もう一度入力して下さい。
   <% end %>
  </div>

  <div class="row border-bottom mt-5">
   <p><i class="bi bi-envelope ml-4 pr-2"></i>お問い合わせ</p>
  </div>

  <%= form_for(@contact, url: confirm_path) do |f| %>

   <div class="form-group row col-md-3 pt-3">
    <%= f.label :name, 'お名前', class: 'col-form-label' %><br>
    <%= f.text_field :name, autofocus: true, class: 'form-control custom-form-control', placeholder: 'お名前を入力して下さい' %>
   </div>

   <div class="form-group row col-md-3 pt-3">
    <%= f.label :email, 'メールアドレス', class: 'col-form-label' %><br>
    <%= f.text_field :email, autofocus: true, class: 'form-control custom-form-control', placeholder: 'メールアドレスを入力して下さい' %>
   </div>

   <div class="form-group row col-md-3 pt-3">
    <%= f.label :message, 'お問い合わせ内容', class: 'col-form-label' %><br>
    <%= f.text_area :message, rows:'10', class: 'form-control custom-form-control', placeholder: 'お問い合わせ内容を入力して下さい' %>
   </div>

  <div class="form-group col-md-2">
    <%= f.submit '入力内容確認', class: 'form-control custom-form-control' %>
  </div>

  <% end %>

</div>

app/views/favorites/_favorite.html.erb
<% if post.favorited_by?(current_user) %>
 <div id="favorite_buttons">
  <%= link_to post_favorites_path(post), class:"text-dark" , method: :delete , remote: true do %>
   <i class="bi bi-hand-thumbs-up-fill pr-2"></i><%= post.favorites.count %>
  <% end %>
 </div>
<% else %>
 <div id="favorite_buttons">
  <%= link_to post_favorites_path(post), class:"text-dark" , method: :post , remote: true do %>
   <i class="bi bi-hand-thumbs-up pr-2"></i><%= post.favorites.count %>
  <% end %>
 </div>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons').html("<%= j(render "favorites/favorite", post: @post) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons').html("<%= j(render "favorites/favorite", post: @post) %>");

app/views/posts/_search.html.erb
 <div class="searchposts mt-4">
  <%= form_with url: search_posts_path, class: 'form-inline', method: :get, local: true do |f| %>
    <%= f.text_field :name, class: 'form-control form-control-sm custom-form-control-2' %>
    <%= f.submit '検索', class: 'btn btn-outline-dark btn-sm ml-2' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row border-bottom mt-5">
   <strong class="mb-3">ぽすとの編集</strong>
  </div>
  <%= form_with model:@post, local: true do |f| %>
   <div class="form-row pt-3">
    <div class="form-group col-md-3">
     <%= f.text_field :title , class: 'form-control custom-form-control', placeholder: 'タイトルを入力' %>
    </div>
   </div>
   <div class="form-row pt-2 ml-1 mb-1">
    <div class="form-group">
     <%= f.select :category_id, @category , { include_blank: 'カテゴリを選択'}, { class: 'form-control custom-form-control' , required: true } %>
    </div>
   </div>
   <div class="form-row pt-3">
    <div class="form-group col-md-3">
     <%= f.text_area :body , rows:'10', class: 'form-control custom-form-control' %>
    </div>
   </div>
   <div class="form-row pt-3">
    <div class="form-group col-md-3">
      <%= f.submit '保存' , class: 'form-control custom-form-control' %>
    </div>
   </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row border-bottom mt-5">

   <% if @category.present? %>
    <strong class="mb-3">
     <i class="bi bi-stars p-2"></i><%= @category.name %>
    </strong>
   <% else %>
    <strong class="mb-3">ねこぽすと</strong>
   <% end %>
  </div>

  <div class="search-form mt-3 mb-5">
   <%= render "posts/search" %>
  </div>
  <% @posts.each do |post| %>
   <div class="row mt-4">
    <table class="container">
     <tbody>
      <tr>
       <td class="col-md-6"><i class="fa fa-chevron-right"><%= link_to post.title, post_path(post.id) , class:"text-dark ml-3 mr-5" %></i></td>
       <td class="col-md-3">by <%= link_to post.user.name, user_path(post.user) , class:"text-dark" %></td>
      </tr>
     </tbody>
    </table>
   </div>
  <% end %>
  <% unless @is_search %>
   <div class="pagenate text-dark">
    <%= paginate @posts %>
   </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">

  <div class="error-text pt-4">
   <% if @post.errors.any? %>
    <i class="bi bi-exclamation-diamond"></i>もう一度入力して下さい。
   <% end %>
  </div>

  <div class="row border-bottom mt-5">
   <strong class="mb-3">新規ぽすと</strong>
  </div>
  <%= form_with model: @post, local:true do |f| %>
   <div class="form-row pt-3">
    <div class="form-group col-md-3">
     <%= f.text_field :title , class: 'form-control custom-form-control', placeholder: 'タイトルを入力' %>
    </div>
   </div>
   <div class="form-row pt-2 ml-1 mb-1">
    <div class="form-group">
     <%= f.select :category_id, @category , { include_blank: 'カテゴリを選択'}, { class: 'form-control custom-form-control' , required: true } %>
    </div>
   </div>
   <div class="form-row pt-2">
    <div class="form-group col-md-3">
     <%= f.attachment_field :post_images_images, multiple: true %>
    </div>
   </div>
   <div class="form-row pt-3">
    <div class="form-group col-md-3">
     <%= f.text_area :body ,rows:'10' , class: 'form-control custom-form-control' %>
    </div>
   </div>
   <div class="form-row pt-3">
    <div class="form-group col-md-3">
      <%= f.submit '投稿' , class: 'form-control custom-form-control' %>
    </div>
   </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row border-bottom mt-5 bd-highlight">
    <div class="me-auto p-2 bd-highlight mr-5">
     <strong><%= @post.title %></strong>
    </div>
    <div class="p-2 bd-highlight ml-5">
    <% if @category.present? %>
     <i class="bi bi-stars p-2"></i>カテゴリ：<%= @category.name %>
    <% else %>
    <% end %>
    <span class="sentiment-score pl-5">
     <i class="bi bi-emoji-smile pr-2"></i>ポジティプスコア：<%= @post.score %>
     <!--余裕があればif文で表示変える-->
    </span>
    </div>
  </div>
  <div class="row mt-5 image-post">
   <% if @post.post_images.present? %>
    <% @post.post_images.each do |image| %>
     <%= attachment_image_tag image, :image, class: "default_image p-3" %>
    <% end %>
   <% else %>
   <% end %>
  </div>
  <div class="row pt-5">
   <!--改行ができるように記述-->
   <p><%=safe_join(@post.body.split("\n"),tag(:br))%></p>
  </div>
  <div class="row border-top pt-3 mt-5">
   <% if @post.user_id == current_user.id %>
    <%= link_to "編集" , edit_post_path , class:"btn btn-outline-dark mr-3" %>
    <%= link_to "削除",post_path(@post), method: :delete , "data-confirm" => "本当に消しますか？" , class:"btn btn-dark" %>
   <% end %>
    <div class="row ml-3">
     <%= render 'favorites/favorite', post: @post %>
     <p class="ml-3"><i class="bi bi-chat mr-2"></i><%= @post.post_comments.count %></p>
    </div>
  </div>
  <div id="comment_area">
   <%= render "post_comments/post_comments", post: @post %>
  </div>
  <div class="row ml-1 mt-4">
    <%= form_with(model:[@post,@post_comment], remote: true) do |f| %>
     <div class="form-group row">
      <%= f.text_area :comment, rows:'2',placeholder: "コメントを入力" , class:"form-control custom-form-control" %>
     </div>
     <div class="form-group row">
      <%= f.submit "送信" , class:"btn btn-outline-dark btn-sm" %>
     </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
 <div class="row border-bottom mt-5">
  <p><i class="bi bi-person-fill ml-4 pr-2"></i>登録情報の編集</p></p>
 </div>
  <%= form_with model:@user, local:true do |f| %>
    <div class="form-group row pt-3">
     <%= f.label 'name', class: 'col-md-3 col-form-label' %><br>
     <%= f.text_field :name, class:'col-md-3 form-control custom-form-control' %>
    </div>
    <div class="form-group row pt-3">
     <%= f.label 'email', class: 'col-md-3 col-form-label' %><br>
     <%= f.email_field :email, autofocus: true, autocomplete: "email", class:'col-md-3 form-control custom-form-control'  %>
    </div>
    <div class="actions form-group mt-3">
     <%= f.submit "保存", class:'col-md-4 btn btn-outline-dark mr-3 mt-4' %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row border-bottom mt-5">
   <strong class="mb-3">
    <%= @user.name %>
    <% if user_signed_in? && @user == current_user %>
     のマイページ
     <span class="edit-user pl-3">
      <%= link_to  edit_user_path(@user), class: 'text-dark' do %>
       <i class="bi bi-gear"></i>
      <% end %>
     </span>
    <% else %>
     のページ
    <% end %>
   </strong>
  </div>
  <% @posts.each do |post| %>
   <div class="row mt-4">
    <span><i class="fa fa-chevron-right"><%= link_to post.title , post_path(post.id) , class:"text-dark ml-3"%></i></span>
   </div>
  <% end %>
</div>