config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:'homes#top'
  get '/about' => 'homes#about'

  resources :categories,only: [:index]
  resources :users, only: [:show ,:edit, :update]
  resources :posts do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    get :search, on: :collection
  end

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/done', to: 'contacts#done', as: 'done'
  get 'contacts/confirm', to: redirect('/contacts/new')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
  
end

app/models/category.rb
class Category < ApplicationRecord

  belongs_to :post, optional: true

end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :name, presence: true
  validates :message, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  accepts_attachments_for :post_images, attachment: :image

  validates :title, presence: true
  validates :body, presence: true

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

end

app/models/post_image.rb
class PostImage < ApplicationRecord
  
  belongs_to :post
  attachment :image
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :posts , dependent: :destroy
         has_many :post_comments,dependent: :destroy
         has_many :favorites,dependent: :destroy
         
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render:new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render:new
  end
  # 入力内容に誤りがあった場合、入力内容を保持したまま前のページに戻ってくれる:back

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render:new
    end
  end

  def done
  end
  # 送信完了画面のための記述

  private

  def contact_params
    params.require(:contact)
          .permit(:email, :name, :message)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @posts = Post.all
    @categories = Category.all
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!
before_action :correct_post,only: [:edit,:update]

  def new
    @post = Post.new
    @category = Category.all.map{ |category| [category.name, category.id,] }
  end

  def create
    @post = Post.new(post_params)
    @post.score = Language.get_data(post_params[:body])
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post.id)
    else
      @category = Category.all.map{ |category| [category.name, category.id,] }
      render :new
    end
  end

  def index
    if params[:category_id].present?
     @category = Category.find(params[:category_id])
     @posts = Post.where(category_id: params[:category_id]).page(params[:page]).reverse_order
     pp @posts
    else
     @posts = Post.page(params[:page]).reverse_order
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    if @post.category_id.present?
     @category = Category.find(@post.category_id)
    end
  end

  def edit
    @post = Post.find(params[:id])
    @category = Category.all.map{ |category| [category.name, category.id,] }
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post)
  end

  def correct_post
    @post = Post.find(params[:id])
   unless @post.user.id == current_user.id
    redirect_to posts_path
   end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def search
    @posts = Post.where('body LIKE ?', "%#{params[:name]}%").or(Post.where('title LIKE ?', "%#{params[:name]}%"))
    @is_search = true
    render :index
  end

  private

  def post_params
    params.require(:post).permit(:title,:body,:category_id, post_images_images: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!
before_action :correct_user, only: [:update,:edit]

def show
  @user = User.find(params[:id])
  @posts = @user.posts
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  @user.update(user_params)
  redirect_to user_path(@user.id)
end

def correct_user
  @user = User.find(params[:id])
 unless @user.id == current_user.id
  redirect_to root_path
 end
end

  private

def user_params
  params.require(:user).permit(:name, :email)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ねこ、暮らし。</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/47864e1775.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>

    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-light shadow-sm p-2 mb-3 bg-white rounded p-20">
        <div class="container">
          <a class="logo" href="/"><%= image_tag 'top-image.jpeg', size: '200x80' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if signed_in? %>
               <li><%= link_to ' マイページ',user_path(current_user.id),class: 'btn btn-outline-dark m-3 btn-sm' %></li>
               <li><%= link_to ' ねこぽすと',posts_path,class: 'btn btn-outline-dark m-3 btn-sm' %></li>
               <li><%= link_to ' ログアウト',destroy_user_session_path, method: :delete , class: 'btn btn-outline-dark m-3 btn-sm' %></li>
               <li><%= link_to ' 新規ぽすと',new_post_path,class: 'btn btn-outline-dark m-3 btn-sm' %></li>
              <% else %>
               <li><%= link_to ' About',about_path,class: 'btn btn-outline-dark m-3 btn-sm' %></li>
               <li><%= link_to ' ねこぽすと',posts_path,class: 'btn btn-outline-dark m-3 btn-sm' %></li>
               <li><%= link_to '  新規登録',new_user_registration_path , class: 'btn btn-outline-dark m-3 btn-sm' %></li>
               <li><%= link_to ' ログイン',new_user_session_path , class: 'btn btn-outline-dark m-3 btn-sm' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>


    <footer class="fixed-bottom">
      <ul class="footer-list">
        <li class="list-main"><i class="bi bi-envelope pr-2"></i><%= link_to 'お問い合わせ', new_contact_path, class: 'text-dark' %></li>
        <li class="list-main"><i class="bi bi-github pr-2"></i><%= link_to 'GitHub', 'https://github.com/arakirina/Cat_living', class: 'text-dark' %></li>
      </ul>
      <small class="copy-right pr-5 pt-3">
        © 2021 Cat_living inc.️
　　　</small>
    </footer>

  </body>

</html>